[build]
  command = 'yarn run build' # Commande pour construire votre projet
  publish = 'dist'            # Répertoire à publier

[dev]
  command = 'yarn run start'   # Commande pour démarrer votre serveur de développement
  port = 5173                   # Port pour le serveur de développement

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

 